vich_uploader:
    db_driver: orm

    mappings:
        avatar:
            uri_prefix: /uploads/avatar
            upload_destination: "%kernel.project_dir%/assets/img/uploads/avatar"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
